### ISSUE TITLE
Csrf LoginPage

### ISSUE THREAD

**Issue by Milanvdm** [ierg4210/shop10#1]
Your csrf value has a static value so it won't be secure.

**Comment by allenpoon** [comment]
My CSRF value is per session, each session generate a new CSRF value.
By CSRF defination, CSRF value is used to defense a Cross origin who cannot get my CSRF value based on same origin policy
The protection is enough
for your reference: please see 
Lecture Note "08-lecture-WebAppSecurityI" Page 16
4. Submitting a ....
 - Implementations
Nonce can be a session id itself or a random and user-specific string / number
so CSRF value can be static for each session

**Comment by Milanvdm** [comment]
Could you show me where the server validates that nonce?
Because I can't seem to find your server code on the master branch of your Git.
