### ISSUE TITLE
[P3B-3] Shopping list information #1

### ISSUE THREAD

**Issue by s1155030186** [ierg4210/shop10#2]
Your shopping list is store on localStorage with following data:
{bookid,quantity, bookname, bookprice}

By requirement, it should

store {pid, number}
request {prod_name, price} from AJAX

![11212402_10205665650294492_1515446157_n](https://cloud.githubusercontent.com/assets/10598196/7537107/b2e5ecda-f5c8-11e4-90c5-28bb448b7153.jpg)
![11225770_10205665680575249_1052283173_n](https://cloud.githubusercontent.com/assets/10598196/7537109/c13042d6-f5c8-11e4-9e18-8210bc08d868.jpg)

![1472287_10205665680335243_1907871988_n](https://cloud.githubusercontent.com/assets/10598196/7537099/a401579a-f5c8-11e4-9679-e50ea4104587.jpg)

Users may change the localStorage so that users can buy products to be cheapest

It expected to change back to a normal product information by sending request to server

From the photo, we can see that when product is updated, the shopping list would not updated.  The wrong decision may be made due to wrong. Or you send the whole things to server and server does not check the relation of the product, it will receive an unexpected total from the client.

prossible fix: Request the price and name by ajax request by using (pid,quantity) and not trust the client local storage directly

**Comment by allenpoon** [comment]
You report in wrong shop :0)
Your report is shop03
THIS IS SHOP10

**Comment by allenpoon** [comment]
your format seem same as my comment in other report
:0) :0) :0) :0) :0) :0) :0) :0) :0) :0) :0) :0)
btw, Enjoy hacking!

**Comment by s1155030186** [comment]
sorry , i see the wrong page
Thanks for ur reminder
